# Generated by Django 3.0.8 on 2020-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOApp', '0002_customerscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerscore',
            name='cstscor',
            field=models.IntegerField(),
        ),
    ]
