# Generated by Django 3.0.8 on 2020-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOApp', '0003_auto_20200719_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='surveyscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('rating', models.IntegerField()),
                ('details', models.CharField(max_length=122)),
            ],
        ),
    ]
