# Generated by Django 3.0.8 on 2020-07-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOApp', '0004_surveyscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyscore',
            name='rating',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=10),
        ),
    ]
