# Generated by Django 3.0.8 on 2020-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOApp', '0005_auto_20200720_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyscore',
            old_name='details',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='surveyscore',
            name='rating',
        ),
        migrations.AddField(
            model_name='surveyscore',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
